# Generated by Django 5.0.6 on 2024-08-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_desiredlocation_tenant_desiredcity_and_more'),
        ('landlord', '0008_rename_is_active_housing_active'),
        ('tenant', '0009_alter_match_options_match_budget_match_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant')),
            ],
            options={
                'unique_together': {('user', 'house')},
            },
        ),
    ]
